const { 
    signup,
    login,
    logout,
    reSendCode,
    addVideo,
    getApprovedVideo,
    getVideoDetails,
    playVideo,
    likeVideo,
    unlikeVideo,
    searchVideo,
    addAudio,
    getAudio,
    getAudioDetails,
    playAudio,
    likeAudio,
    unlikeAudio,
    searchAudio,
    addBlog,
    getApprovedBlog,
    getBlogDetail,
    likeBlog,
    unlikeBlog,
    searchBlog,
    comment,
    replyComment,
    upvoteComment,
    deleteComment
} = require('./userController')

const {
    verifyEmail,
    resetPassword
} = require('./emailController')
module.exports = {
    signup,
    login,
    logout,
    reSendCode,
    verifyEmail,
    resetPassword,
    addVideo,
    getApprovedVideo,
    getVideoDetails,
    playVideo,
    likeVideo,
    unlikeVideo,
    searchVideo,
    addAudio,
    getAudio,
    getAudioDetails,
    playAudio,
    likeAudio,
    unlikeAudio,
    searchAudio,
    addBlog,
    getApprovedBlog,
    getBlogDetail,
    likeBlog,
    unlikeBlog,
    searchBlog,
    comment,
    replyComment,
    upvoteComment,
    deleteComment
}
